// <auto-generated />
using System;
using BDH.Rhino.Web.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BDH.Rhino.Web.API.Migrations
{
    [DbContext(typeof(BDHRhinoWebContext))]
    [Migration("20221017134042_ibouwconcept")]
    partial class ibouwconcept
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.BuildingConceptGeometry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("BuildingConceptGeometries");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.KnownBuildingConcept", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BouwkostenPerBVO")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BvoPerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("GeometryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("M3PerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MeerprijsBENG")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MeerprijsEPC")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GeometryId");

                    b.ToTable("OpenBouwConcepten");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BaseGeometryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BasePolygon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmailAdress")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BaseGeometryId");

                    b.HasIndex("UserEmailAdress");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.ProjectGeometryBase", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("ExistingBuildings")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectBaseGeometries");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.ProjectVersion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Assets")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Boxes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tiles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VersionGeometryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ways")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("VersionGeometryId");

                    b.ToTable("ProjectVersions");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.ProjectVersionGeometry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectVersionGeometries");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.User", b =>
                {
                    b.Property<string>("EmailAdress")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuthenticationKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.HasKey("EmailAdress");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.UserProduct", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("BvoPerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GeometryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("M3PerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MeerprijsBENG")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MeerprijsEPC")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserEmailAdress")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GeometryId");

                    b.HasIndex("UserEmailAdress");

                    b.ToTable("UserProducts");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.UserProductGeometry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("UserProductGeometries");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.KnownBuildingConcept", b =>
                {
                    b.HasOne("BDH.Rhino.Web.Domain.Models.BuildingConceptGeometry", "Geometry")
                        .WithMany()
                        .HasForeignKey("GeometryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Geometry");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.Project", b =>
                {
                    b.HasOne("BDH.Rhino.Web.Domain.Models.ProjectGeometryBase", "BaseGeometry")
                        .WithMany()
                        .HasForeignKey("BaseGeometryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BDH.Rhino.Web.Domain.Models.User", null)
                        .WithMany("Projects")
                        .HasForeignKey("UserEmailAdress");

                    b.Navigation("BaseGeometry");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.ProjectVersion", b =>
                {
                    b.HasOne("BDH.Rhino.Web.Domain.Models.Project", null)
                        .WithMany("Versions")
                        .HasForeignKey("ProjectId");

                    b.HasOne("BDH.Rhino.Web.Domain.Models.ProjectVersionGeometry", "VersionGeometry")
                        .WithMany()
                        .HasForeignKey("VersionGeometryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VersionGeometry");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.UserProduct", b =>
                {
                    b.HasOne("BDH.Rhino.Web.Domain.Models.UserProductGeometry", "Geometry")
                        .WithMany()
                        .HasForeignKey("GeometryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BDH.Rhino.Web.Domain.Models.User", null)
                        .WithMany("Products")
                        .HasForeignKey("UserEmailAdress");

                    b.Navigation("Geometry");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.Project", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.User", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
