// <auto-generated />
using System;
using BDH.Rhino.Web.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BDH.Rhino.Web.API.Migrations
{
    [DbContext(typeof(BDHRhinoWebContext))]
    [Migration("20230301083541_add-stapelbaar")]
    partial class addstapelbaar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.Entities.BuildingConcept", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BouwkostenPerBVO")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BvoPerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("GeometryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("M3PerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MeerprijsBENG")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MeerprijsEPC")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Stapelbaar")
                        .HasColumnType("bit");

                    b.Property<int>("WoningenPerUnit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GeometryId");

                    b.ToTable("OpenBouwConcepten");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.Entities.BuildingConceptGeometry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("BuildingConceptGeometries");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.Entities.BuildingConceptTransformationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BouwconceptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LocationX")
                        .HasColumnType("float");

                    b.Property<double>("LocationY")
                        .HasColumnType("float");

                    b.Property<string>("ProjectVersionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Rotation")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProjectVersionId");

                    b.ToTable("BuildingConceptTransformations");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.Entities.Company", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.Entities.GenericMassTransformationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BouwconceptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Depth")
                        .HasColumnType("float");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("LocationX")
                        .HasColumnType("float");

                    b.Property<double>("LocationY")
                        .HasColumnType("float");

                    b.Property<string>("ProjectVersionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Rotation")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProjectVersionId");

                    b.ToTable("GenericMassTransformations");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.Entities.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BaseGeometryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BasePolygon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVersion2Compatible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmailAdress")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BaseGeometryId");

                    b.HasIndex("UserEmailAdress");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.Entities.ProjectVersion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Assets")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Boxes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVersion2Compatible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tiles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VersionGeometryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ways")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("VersionGeometryId");

                    b.ToTable("ProjectVersions");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.Entities.User", b =>
                {
                    b.Property<string>("EmailAdress")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuthenticationKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.HasKey("EmailAdress");

                    b.HasIndex("CompanyName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.Entities.UserProduct", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("BvoPerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeometryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("M3PerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MeerprijsBENG")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MeerprijsEPC")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserEmailAdress")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WoningenPerUnit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GeometryId");

                    b.HasIndex("UserEmailAdress");

                    b.ToTable("UserProducts");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.Entities.UserProductGeometry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("UserProductGeometries");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.Obsolete.ProjectGeometryBase", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("ExistingBuildings")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectBaseGeometries");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.ProjectVersionGeometry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectVersionGeometries");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.Entities.BuildingConcept", b =>
                {
                    b.HasOne("BDH.Rhino.Web.Domain.Models.Entities.BuildingConceptGeometry", "Geometry")
                        .WithMany()
                        .HasForeignKey("GeometryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Geometry");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.Entities.BuildingConceptTransformationEntity", b =>
                {
                    b.HasOne("BDH.Rhino.Web.Domain.Models.Entities.ProjectVersion", null)
                        .WithMany("BouwconceptTransformations")
                        .HasForeignKey("ProjectVersionId");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.Entities.GenericMassTransformationEntity", b =>
                {
                    b.HasOne("BDH.Rhino.Web.Domain.Models.Entities.ProjectVersion", null)
                        .WithMany("GenericMassTransformations")
                        .HasForeignKey("ProjectVersionId");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.Entities.Project", b =>
                {
                    b.HasOne("BDH.Rhino.Web.Domain.Models.Obsolete.ProjectGeometryBase", "BaseGeometry")
                        .WithMany()
                        .HasForeignKey("BaseGeometryId");

                    b.HasOne("BDH.Rhino.Web.Domain.Models.Entities.User", null)
                        .WithMany("Projects")
                        .HasForeignKey("UserEmailAdress");

                    b.Navigation("BaseGeometry");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.Entities.ProjectVersion", b =>
                {
                    b.HasOne("BDH.Rhino.Web.Domain.Models.Entities.Project", null)
                        .WithMany("Versions")
                        .HasForeignKey("ProjectId");

                    b.HasOne("BDH.Rhino.Web.Domain.Models.ProjectVersionGeometry", "VersionGeometry")
                        .WithMany()
                        .HasForeignKey("VersionGeometryId");

                    b.Navigation("VersionGeometry");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.Entities.User", b =>
                {
                    b.HasOne("BDH.Rhino.Web.Domain.Models.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyName");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.Entities.UserProduct", b =>
                {
                    b.HasOne("BDH.Rhino.Web.Domain.Models.Entities.UserProductGeometry", "Geometry")
                        .WithMany()
                        .HasForeignKey("GeometryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BDH.Rhino.Web.Domain.Models.Entities.User", null)
                        .WithMany("Products")
                        .HasForeignKey("UserEmailAdress");

                    b.Navigation("Geometry");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.Entities.Project", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.Entities.ProjectVersion", b =>
                {
                    b.Navigation("BouwconceptTransformations");

                    b.Navigation("GenericMassTransformations");
                });

            modelBuilder.Entity("BDH.Rhino.Web.Domain.Models.Entities.User", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
