// <auto-generated />
using System;
using BDH.Rhino.Web.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BDH.Rhino.Web.API.Migrations
{
    [DbContext(typeof(BDHRhinoWebContext))]
    [Migration("20230419074239_configuration-properties")]
    partial class configurationproperties
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.BouwconceptGeometry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("BouwconceptGeometries");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.BuildingConcept", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BvoPerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByEmailAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("GeometryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<decimal>("M3PerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MeerprijsBENG")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MeerprijsEPC")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ProductieKostenPerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Stapelbaar")
                        .HasColumnType("bit");

                    b.Property<int>("WoningenPerUnit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.HasIndex("CreatedByEmailAdress");

                    b.HasIndex("GeometryId");

                    b.HasIndex("OwnerName");

                    b.ToTable("Bouwconcepten");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.BuildingConceptCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerName");

                    b.ToTable("BuildingConceptCatalogs");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.BuildingConceptConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AboveIsIndifferent")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowedOnLowestLevel")
                        .HasColumnType("bit");

                    b.Property<bool>("BelowIsIndifferent")
                        .HasColumnType("bit");

                    b.Property<int>("ColumnSpan")
                        .HasColumnType("int");

                    b.Property<bool>("EmptySpaceAllowedAbove")
                        .HasColumnType("bit");

                    b.Property<bool>("EmptySpaceAllowedLeft")
                        .HasColumnType("bit");

                    b.Property<bool>("EmptySpaceAllowedRight")
                        .HasColumnType("bit");

                    b.Property<Guid>("ForId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("LeftIsIndifferent")
                        .HasColumnType("bit");

                    b.Property<bool>("RightIsIndifferent")
                        .HasColumnType("bit");

                    b.Property<int>("RowSpan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ForId");

                    b.ToTable("BuildingConceptConfigurations");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.BuildingConceptTransformationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BouwconceptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LocationX")
                        .HasColumnType("float");

                    b.Property<double>("LocationY")
                        .HasColumnType("float");

                    b.Property<string>("ProjectVersionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Rotation")
                        .HasColumnType("float");

                    b.Property<int>("Verdiepingen")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectVersionId");

                    b.ToTable("BuildingConceptTransformations");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.Company", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.GenericMassTransformationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BouwconceptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BouwkostenTypologie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Depth")
                        .HasColumnType("float");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("LocationX")
                        .HasColumnType("float");

                    b.Property<double>("LocationY")
                        .HasColumnType("float");

                    b.Property<string>("ProjectVersionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Rotation")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProjectVersionId");

                    b.ToTable("GenericMassTransformations");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BasePolygon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVersion2Compatible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmailAdress")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserEmailAdress");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.ProjectVersion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsVersion2Compatible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ways")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectVersions");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.SchoolProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BasePolygon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerEmailAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerEmailAdress");

                    b.ToTable("SchoolProjects");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.SchoolProjectVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowDisconnected")
                        .HasColumnType("bit");

                    b.Property<double>("GridHeight")
                        .HasColumnType("float");

                    b.Property<double>("GridRotation")
                        .HasColumnType("float");

                    b.Property<double>("GridSize")
                        .HasColumnType("float");

                    b.Property<double>("GridTranslation")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Obstacles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SchoolProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Seed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolProjectId");

                    b.ToTable("SchoolProjectVersions");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.SchoolProjectVersionCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("BVO")
                        .HasColumnType("float");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FixedPoints")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HighestLevel")
                        .HasColumnType("int");

                    b.Property<int>("Levels")
                        .HasColumnType("int");

                    b.Property<int>("LowestLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SchoolProjectVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SchoolProjectVersionId");

                    b.ToTable("SchoolProjectVersionClusters");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.User", b =>
                {
                    b.Property<string>("EmailAdress")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuthenticationKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.HasKey("EmailAdress");

                    b.HasIndex("CompanyName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.UserFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BouwconceptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserEmailAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BouwconceptId");

                    b.HasIndex("UserEmailAdress");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.BuildingConcept", b =>
                {
                    b.HasOne("BDH.Rhino.Web.API.Domain.Entities.BuildingConceptCatalog", "Catalog")
                        .WithMany("BuildingConcepts")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BDH.Rhino.Web.API.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByEmailAdress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BDH.Rhino.Web.API.Domain.Entities.BouwconceptGeometry", "Geometry")
                        .WithMany()
                        .HasForeignKey("GeometryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BDH.Rhino.Web.API.Domain.Entities.Company", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");

                    b.Navigation("CreatedBy");

                    b.Navigation("Geometry");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.BuildingConceptCatalog", b =>
                {
                    b.HasOne("BDH.Rhino.Web.API.Domain.Entities.Company", "Owner")
                        .WithMany("Catalogs")
                        .HasForeignKey("OwnerName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.BuildingConceptConfiguration", b =>
                {
                    b.HasOne("BDH.Rhino.Web.API.Domain.Entities.BuildingConcept", "For")
                        .WithMany()
                        .HasForeignKey("ForId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("For");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.BuildingConceptTransformationEntity", b =>
                {
                    b.HasOne("BDH.Rhino.Web.API.Domain.Entities.ProjectVersion", null)
                        .WithMany("BouwconceptTransformations")
                        .HasForeignKey("ProjectVersionId");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.GenericMassTransformationEntity", b =>
                {
                    b.HasOne("BDH.Rhino.Web.API.Domain.Entities.ProjectVersion", null)
                        .WithMany("GenericMassTransformations")
                        .HasForeignKey("ProjectVersionId");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.Project", b =>
                {
                    b.HasOne("BDH.Rhino.Web.API.Domain.Entities.User", null)
                        .WithMany("Projects")
                        .HasForeignKey("UserEmailAdress");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.ProjectVersion", b =>
                {
                    b.HasOne("BDH.Rhino.Web.API.Domain.Entities.Project", null)
                        .WithMany("Versions")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.SchoolProject", b =>
                {
                    b.HasOne("BDH.Rhino.Web.API.Domain.Entities.User", "Owner")
                        .WithMany("SchoolProjects")
                        .HasForeignKey("OwnerEmailAdress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.SchoolProjectVersion", b =>
                {
                    b.HasOne("BDH.Rhino.Web.API.Domain.Entities.SchoolProject", null)
                        .WithMany("Versies")
                        .HasForeignKey("SchoolProjectId");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.SchoolProjectVersionCluster", b =>
                {
                    b.HasOne("BDH.Rhino.Web.API.Domain.Entities.SchoolProjectVersion", null)
                        .WithMany("Clusters")
                        .HasForeignKey("SchoolProjectVersionId");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.User", b =>
                {
                    b.HasOne("BDH.Rhino.Web.API.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyName");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.UserFavorite", b =>
                {
                    b.HasOne("BDH.Rhino.Web.API.Domain.Entities.BuildingConcept", "Bouwconcept")
                        .WithMany()
                        .HasForeignKey("BouwconceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BDH.Rhino.Web.API.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserEmailAdress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bouwconcept");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.BuildingConceptCatalog", b =>
                {
                    b.Navigation("BuildingConcepts");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.Company", b =>
                {
                    b.Navigation("Catalogs");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.Project", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.ProjectVersion", b =>
                {
                    b.Navigation("BouwconceptTransformations");

                    b.Navigation("GenericMassTransformations");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.SchoolProject", b =>
                {
                    b.Navigation("Versies");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.SchoolProjectVersion", b =>
                {
                    b.Navigation("Clusters");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.User", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("SchoolProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
