// <auto-generated />
using System;
using BDH.Rhino.Web.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BDH.Rhino.Web.API.Migrations
{
    [DbContext(typeof(BDHRhinoWebContext))]
    [Migration("20230330100716_changed-productiekosten-column")]
    partial class changedproductiekostencolumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.Bouwconcept", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BvoPerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("GeometryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<decimal>("M3PerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MeerprijsBENG")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MeerprijsEPC")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ProductieKostenPerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Stapelbaar")
                        .HasColumnType("bit");

                    b.Property<int>("WoningenPerUnit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GeometryId");

                    b.HasIndex("OwnerName");

                    b.ToTable("Bouwconcepten");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.BouwconceptGeometry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("BouwconceptGeometries");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.BuildingConceptTransformationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BouwconceptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LocationX")
                        .HasColumnType("float");

                    b.Property<double>("LocationY")
                        .HasColumnType("float");

                    b.Property<string>("ProjectVersionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Rotation")
                        .HasColumnType("float");

                    b.Property<int>("Verdiepingen")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectVersionId");

                    b.ToTable("BuildingConceptTransformations");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.Company", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.GenericMassTransformationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BouwconceptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Depth")
                        .HasColumnType("float");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("LocationX")
                        .HasColumnType("float");

                    b.Property<double>("LocationY")
                        .HasColumnType("float");

                    b.Property<string>("ProjectVersionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Rotation")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProjectVersionId");

                    b.ToTable("GenericMassTransformations");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BasePolygon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVersion2Compatible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmailAdress")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserEmailAdress");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.ProjectVersion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsVersion2Compatible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ways")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectVersions");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.User", b =>
                {
                    b.Property<string>("EmailAdress")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuthenticationKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.HasKey("EmailAdress");

                    b.HasIndex("CompanyName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.Bouwconcept", b =>
                {
                    b.HasOne("BDH.Rhino.Web.API.Domain.Entities.BouwconceptGeometry", "Geometry")
                        .WithMany()
                        .HasForeignKey("GeometryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BDH.Rhino.Web.API.Domain.Entities.Company", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Geometry");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.BuildingConceptTransformationEntity", b =>
                {
                    b.HasOne("BDH.Rhino.Web.API.Domain.Entities.ProjectVersion", null)
                        .WithMany("BouwconceptTransformations")
                        .HasForeignKey("ProjectVersionId");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.GenericMassTransformationEntity", b =>
                {
                    b.HasOne("BDH.Rhino.Web.API.Domain.Entities.ProjectVersion", null)
                        .WithMany("GenericMassTransformations")
                        .HasForeignKey("ProjectVersionId");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.Project", b =>
                {
                    b.HasOne("BDH.Rhino.Web.API.Domain.Entities.User", null)
                        .WithMany("Projects")
                        .HasForeignKey("UserEmailAdress");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.ProjectVersion", b =>
                {
                    b.HasOne("BDH.Rhino.Web.API.Domain.Entities.Project", null)
                        .WithMany("Versions")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.User", b =>
                {
                    b.HasOne("BDH.Rhino.Web.API.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyName");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.Project", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.ProjectVersion", b =>
                {
                    b.Navigation("BouwconceptTransformations");

                    b.Navigation("GenericMassTransformations");
                });

            modelBuilder.Entity("BDH.Rhino.Web.API.Domain.Entities.User", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
